from __future__ import annotations
from dataclasses import dataclass
from typing import Tuple, Optional
import numpy as np
from scipy.spatial import ConvexHull

@dataclass
class HullStats:
    n_input_vertices: int
    n_hull_simplices: int
    volume: float
    area: float
    bbox_min: Tuple[float, float, float]
    bbox_max: Tuple[float, float, float]

def convex_hull(vertices: np.ndarray) -> ConvexHull:
    """3D convex hull of vertices (expects (M,3))."""
    if vertices.ndim != 2 or vertices.shape[1] != 3:
        raise ValueError("vertices must be (M,3)")
    return ConvexHull(vertices)

def hull_stats(vertices: np.ndarray, hull: Optional[ConvexHull] = None) -> HullStats:
    if hull is None:
        hull = convex_hull(vertices)
    vmin = tuple(np.min(vertices, axis=0).tolist())
    vmax = tuple(np.max(vertices, axis=0).tolist())
    return HullStats(
        n_input_vertices=int(vertices.shape[0]),
        n_hull_simplices=int(hull.simplices.shape[0]),
        volume=float(hull.volume),
        area=float(hull.area),
        bbox_min=vmin,
        bbox_max=vmax,
    )

def export_obj(vertices: np.ndarray, hull: ConvexHull, path: str) -> None:
    """Export convex hull surface triangles as OBJ."""
    with open(path, "w", encoding="utf-8") as f:
        f.write("# generated by collatz_rupert_delay_embedding\n")
        for p in vertices:
            f.write(f"v {p[0]} {p[1]} {p[2]}\n")
        for tri in hull.simplices:
            a, b, c = tri.tolist()
            f.write(f"f {a+1} {b+1} {c+1}\n")
